Scaffold2/Controllers/CalendarController.cs
using Microsoft.AspNetCore.Mvc;
using Scaffold2.Models;

namespace Scaffold2.Controllers
{
    public class CalendarController : Controller
    {
        public readonly CalendarDBContext db;
        public CalendarController(CalendarDBContext calendarDBContext)
        {
            db = calendarDBContext;
        }
        [HttpGet("/calendar")]
        public IActionResult Index()
        {
            return View(db.Calendar.ToList());
        }
        [HttpGet("/calendar/create")]
        public IActionResult Create(CalendarModel calendarModel)
        {
            return View(calendarModel);
        }

        [HttpPost("/calendar/create")]
        public IActionResult CreateEvent(CalendarModel calendarModel)
        {
            if (ModelState.IsValid)
            {
                db.Calendar.Add(calendarModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Create", calendarModel);
        }
        [HttpGet("/calendar/edit/{Id}")]
        public IActionResult Edit(int Id)
        {
            var calEvent = db.Calendar.FirstOrDefault(x => x.Id == Id);
            return View(calEvent);
        }
        [HttpPost("/calendar/edit/{Id}")]
        public IActionResult Edit(int Id, [FromBody]CalendarModel calendarModel)
        {
            var calEvent = db.Calendar.FirstOrDefault(x => x.Id == Id);
            calEvent.eventTitle = calendarModel.eventTitle;
            calEvent.eventDate = calendarModel.eventDate;
            calEvent.eventDescription = calendarModel.eventDescription;
            if (!ModelState.IsValid)
            {
                return View("Index", calendarModel);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpDelete("/calendar/delete/{Id}")]
        public IActionResult DeleteEvent(int id)
        {
            var calEvent = db.Calendar.First(x => x.Id == id);
            db.Calendar.Remove(calEvent);
            db.SaveChanges();
            return Ok(new { Ok = true });
        }
    }
}

Scaffold2/Controllers/MapController.cs
using Microsoft.AspNetCore.Mvc;
using Scaffold2.Models;

namespace Scaffold2.Controllers
{
    public class MapController : Controller
    {
        public readonly MapDBContext db;
        public MapController(MapDBContext mapDBContext)
        {
            db = mapDBContext;
        }
        [HttpGet("/map")]
        public IActionResult Index()
        {
            return View(db.News.ToList());
        }
        [HttpGet("/map/create/{lat}/{lng}")]
        public IActionResult Create(string lat, string lng)
        {
            return View(new MapMarker
            {
                lat=lat,
                lng=lng
            });
        }
        [HttpPost("/map/create")] 
        public IActionResult Create(MapMarker marker)
        {
            if (ModelState.IsValid)
            {
                db.News.Add(marker);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Create", marker);
        }
        [HttpGet("/map/edit/{Id}")]
        public IActionResult Edit(int Id)
        {
            var marker = db.News.FirstOrDefault(x => x.Id == Id);
            return View(marker);
        }
        [HttpPost("/map/edit/{Id}")]
        public IActionResult Edit(int Id,MapMarker marker)
        {
            var varmarker = db.News.FirstOrDefault(x => x.Id == Id);
            varmarker.title = marker.title;
            varmarker.lat = marker.lat;
            varmarker.lng = marker.lng;
            if (!ModelState.IsValid)
            {
                return View("Index", marker);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost("/map/delete/{Id}")]
        public IActionResult Delete(int id)
        {
            var varmarker = db.News.First(x => x.Id == id);
            db.News.Remove(varmarker);
            db.SaveChanges();
            return Ok(new {Ok=true});
        }
    }
}

Scaffold2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Scaffold2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Scaffold2.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
          crossorigin="" />
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
            integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
            crossorigin=""></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.27/dist/sweetalert2.all.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.27/dist/sweetalert2.min.css" rel="stylesheet">
   
    
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.5.0/main.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@5.5.0/main.css" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Scaffold2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Map" asp-action="Index">Map</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calendar" asp-action="Index">Calendar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
                <partial name ="_LoginPartial"/>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Scaffold2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>